{% set version = "0.0.20" %}

package:
  name: xskillscore
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/x/xskillscore/xskillscore-{{ version }}.tar.gz
  sha256: 402eb1502b3c2b8837b74ce1e60b59596f95856fed489ba673cec267fca55d4b

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python >=3.7
    - bottleneck
    - cftime
    - dask
    - numba >=0.52
    - numpy
    - properscoring
    - scikit-learn
    - scipy
    - xarray >=0.16.1
    - xhistogram ==0.1.2

test:
  imports:
    - xskillscore
    - xskillscore.core

about:
  home: https://github.com/xarray-contrib/xskillscore
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Metrics for verifying forecasts 
  doc_url: http://xskillscore.readthedocs.io
  dev_url: https://github.com/xarray-contrib/xskillscore

extra:
  recipe-maintainers:
    - ocefpaf
    - raybellwaves
    - bradyrx
    - aaronspring
