{% set version = "0.0.4" %}

package:
  name: xskillscore
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/x/xskillscore/xskillscore-{{ version }}.tar.gz
  sha256: 029067c34078f0f9727c9bc5e13b1009d89bc45e9e318b9fc5651ab81c970887

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - dask
    - properscoring
    - scikit-learn
    - scipy
    - xarray

test:
  imports:
    - xskillscore
    - xskillscore.core

about:
  home: https://github.com/raybellwaves/xskillscore
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: xskillscore

extra:
  recipe-maintainers:
    - ocefpaf
    - raybellwaves
