{% set version = "0.0.19" %}

package:
  name: xskillscore
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/x/xskillscore/xskillscore-{{ version }}.tar.gz
  sha256: 6291f373f5686f30a87c932cec0f0bf4e6d6cb4ab412e3d943d8407a36aa5d4f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python >=3.7
    - bottleneck
    - cftime
    - dask <=2021.02.0
    - numba >=0.52
    - numpy
    - properscoring
    - scikit-learn
    - scipy
    - xarray >=0.16.1
    - xhistogram >=0.1.2

test:
  imports:
    - xskillscore
    - xskillscore.core

about:
  home: https://github.com/xarray-contrib/xskillscore
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Metrics for verifying forecasts 
  doc_url: http://xskillscore.readthedocs.io
  dev_url: https://github.com/raybellwaves/xskillscore

extra:
  recipe-maintainers:
    - ocefpaf
    - raybellwaves
    - bradyrx
    - aaronspring
