{% set version = "0.0.17" %}

package:
  name: xskillscore
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/x/xskillscore/xskillscore-{{ version }}.tar.gz
  sha256: 636b67955b0ac6f9e5aafb1a19f2ae5fd5ccb7a5568bb53df09d80bd2bfbd88e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python >=3.6
    - bottleneck
    - cftime
    - dask
    - numba
    - numpy
    - properscoring
    - scikit-learn
    - scipy
    - xarray
    - xhistogram

test:
  imports:
    - xskillscore
    - xskillscore.core

about:
  home: https://github.com/raybellwaves/xskillscore
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Metrics for verifying forecasts 
  doc_url: http://xskillscore.readthedocs.io
  dev_url: https://github.com/raybellwaves/xskillscore

extra:
  recipe-maintainers:
    - ocefpaf
    - raybellwaves
    - bradyrx
    - aaronspring
