{% set version = "0.0.28" %}

package:
  name: xskillscore
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/x/xskillscore/xskillscore-{{ version }}.tar.gz
  sha256: e003bba66d2d244524f5b9fa9b152a71b09646d25beda42622b0eb7fd84c05c5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python >={{ python_min }}
    - bottleneck
    - cftime
    - dask
    - numba >=0.52
    - numpy
    - properscoring
    - scikit-learn
    - scipy
    - statsmodels
    - xarray >=0.16.1
    - xhistogram >=0.3.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - xskillscore
    - xskillscore.core

about:
  home: https://github.com/xarray-contrib/xskillscore
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Metrics for verifying forecasts
  doc_url: http://xskillscore.readthedocs.io
  dev_url: https://github.com/xarray-contrib/xskillscore

extra:
  recipe-maintainers:
    - ocefpaf
    - raybellwaves
    - bradyrx
    - aaronspring
