{% set version = "0.0.26" %}

package:
  name: xskillscore
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/x/xskillscore/xskillscore-{{ version }}.tar.gz
  sha256: 780a424c1ab3eedf526a45ba8e6cf6dca61b17339252115a4e25ea8c5833ada5

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python >={{ python_min }}
    - bottleneck
    - cftime
    - dask
    - numba >=0.52
    - numpy
    - properscoring
    - scikit-learn
    - scipy
    - statsmodels
    - xarray >=0.16.1
    - xhistogram >=0.3.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - xskillscore
    - xskillscore.core

about:
  home: https://github.com/xarray-contrib/xskillscore
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Metrics for verifying forecasts
  doc_url: http://xskillscore.readthedocs.io
  dev_url: https://github.com/xarray-contrib/xskillscore

extra:
  recipe-maintainers:
    - ocefpaf
    - raybellwaves
    - bradyrx
    - aaronspring
