{% set version = "0.0.11" %}

package:
  name: xskillscore
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/x/xskillscore/xskillscore-{{ version }}.tar.gz
  sha256: 114ddedaf47a83cb7c24db3d2ea1f9bc4d786ef73e17da851849ea0ba98ed90f

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - dask
    - properscoring
    - scikit-learn
    - scipy
    - xarray
    - numba
    - bottleneck

test:
  imports:
    - xskillscore
    - xskillscore.core

about:
  home: https://github.com/raybellwaves/xskillscore
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: xskillscore

extra:
  recipe-maintainers:
    - ocefpaf
    - raybellwaves
