travis:
  secure:
    BINSTAR_TOKEN: mYzpZg75Xv+2vC0xyF7hhrx5E4Bdl7cRl6OWyaT8ptU+NOjRkSLB43TffHbLpzSZT6AImn8HOJCjpPFuPruviRpPOZnn4pZ+WegVBGgfhh5h3ZE8X1rmisSsXVkSBSzzDQPj95LH8SnPvqByQggPwZrlwsSjuLRGLrJOJeAJVFz03huPFxVQO1SCuTLjFlP5QnenuM1LOo8kj0VI0U3p87m5PmMYA3wXz3reGSpBgDBjCpaTltFv/EnnltMBz15CVROVNk9xkh3UuKYVpeB87b8Ua0lPeqGq8ozMUlI4Ovc6jUHNPyJ+XByEn8TVpp+6HqdwHV8ODCRlvxNnZOnNsz/LP+/vVk3e36/FiyK4F29PO31cQSjnB657sDNMiMi9uG3W+uewx6j3fGaZ4rSI9SW4TdfmukOxj16kQlLwbcXmKzOysHxTUf8KtmKKBPovouYZ6obcakpQtsI6G5K+0eYD5dzQrMJmTYcRNOrka9woNbjgsp6vuds6uWPCmbHNotcXDZd6y2TbPuoWbvInT+5RJXwF9/okYSTCdPSxUBfbODMw/7O7A+cX/aLLL8i4FjqKOFs2y9rr03rOB9txrBS0T6RBTIuYT8KAsHLW8YuF2Z7Z8jjAx7De3RW04xtfWvuLw84vQy0F0BMXypGovLwuO6WMhZeDRsArqVXNl2w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
